---
- name: "{{ exporter_name }}: Add exporter service"
  ansible.builtin.include_tasks:
    file: service.yml
  when: exporter_install | bool

- name: "{{ exporter_name }}: Install and configure caddy"
  ansible.builtin.include_tasks:
    file: caddy.yml
  when: exporter_configure_caddy | bool

- name: "{{ exporter_name }}: Register"
  ansible.builtin.include_tasks:
    file: register.yml
  when: exporter_register | bool
