---
- name: "{{ exporter_name }}: Add systemd service"
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ exporter_service }}.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: "{{ exporter_handler }}"

- name: "{{ exporter_name }}: Start and enable systemd service"
  ansible.builtin.systemd:
    name: "{{ exporter_service }}.service"
    daemon_reload: true
    enabled: true
    state: started
